package com.project.codelight.global.exception;

import lombok.Getter;

@Getter
public enum ExceptionCode {
    // ========== 전체/공통 ==========
    INTERNAL_SERVER_ERROR,
    INVALID_PARAMETER,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    UNAUTHORIZED_ACCESS,
    FORBIDDEN_ACCESS,

    // ========== 인증/인가 (AUTH) ==========
    // 회원가입
    USER_EMAIL_ALREADY_USED,
    USER_PASSWORD_POLICY_VIOLATION,
    USER_EMAIL_INVALID_FORMAT,

    // 로그인
    USER_NOT_FOUND,
    USER_LOGIN_REQUEST_ERROR,
    USER_INVALID_CREDENTIALS,
    USER_INVALID_PASSWORD,
    USER_ACCOUNT_DELETED,
    USER_ACCOUNT_BANNED,

    // 토큰
    TOKEN_NOT_FOUND,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    TOKEN_REFRESH_FAILED,
    TOKEN_BLACKLISTED,

    // OAuth2
    OAUTH_PROVIDER_ERROR,
    OAUTH_INVALID_STATE,
    OAUTH_CALLBACK_ERROR,
    OAUTH_TOKEN_REQUEST_FAILED,
    OAUTH_USER_INFO_REQUEST_FAILED,
    OAUTH_SERVER_ERROR,
    OAUTH_EMAIL_NOT_PROVIDED,

    // 권한
    INSUFFICIENT_PERMISSION,
    ADMIN_ONLY,
    PRESENTER_ONLY,

    // ========== 공지사항 (NOTICE) ==========
    NOTICE_NOT_FOUND,
    NOTICE_TITLE_REQUIRED,
    NOTICE_CONTENT_REQUIRED,
    NOTICE_XSS_DETECTED,
    NOTICE_NOT_OWNED_BY_USER,
    NOTICE_ALREADY_DELETED,

    // ========== 마이페이지 (PROFILE) ==========
    PROFILE_NOT_FOUND,
    PROFILE_NICKNAME_DUPLICATED,
    PROFILE_NICKNAME_INVALID,
    PROFILE_BIO_TOO_LONG,
    PROFILE_INVALID_URL,

    // 아바타/이미지
    IMAGE_FILE_REQUIRED,
    IMAGE_SIZE_EXCEEDED,
    IMAGE_INVALID_FORMAT,
    IMAGE_UPLOAD_FAILED,
    S3_PRESIGNED_URL_ERROR,

    // ========== 피드 (POST) ==========
    POST_NOT_FOUND,
    POST_CONTENT_REQUIRED,
    POST_CONTENT_TOO_LONG,
    POST_NOT_OWNED_BY_USER,
    POST_ALREADY_DELETED,
    POST_INVALID_CURSOR,

    // 링크 프리뷰
    LINK_PREVIEW_FETCH_FAILED,
    LINK_PREVIEW_INVALID_URL,
    LINK_PREVIEW_TIMEOUT,

    // 파일 첨부
    POST_FILE_COUNT_EXCEEDED,
    GIF_SIZE_EXCEEDED,
    GIF_FRAME_EXCEEDED,
    FILE_UPLOAD_FAILED,

    // 리액션/상호작용
    EMOJI_INVALID,
    LIKE_ALREADY_EXISTS,
    LIKE_NOT_FOUND,

    // 댓글
    COMMENT_NOT_FOUND,
    COMMENT_CONTENT_REQUIRED,
    COMMENT_CONTENT_TOO_LONG,
    COMMENT_NOT_OWNED_BY_USER,
    COMMENT_ALREADY_REPORTED,

    // ========== 투표 (POLL) ==========
    POLL_NOT_FOUND,
    POLL_OPTIONS_REQUIRED,
    POLL_OPTIONS_EXCEEDED,
    POLL_OPTION_DUPLICATED,
    POLL_MULTIPLE_VOTE_NOT_ALLOWED,
    POLL_ALREADY_VOTED,
    POLL_ALREADY_EXISTS,
    UNAUTHORIZED,

    // ========== 발표 (PRESENTATION) ==========
    // 일정
    PRESENTATION_NOT_FOUND,
    PRESENTATION_TITLE_REQUIRED,
    PRESENTATION_INVALID_DURATION,
    PRESENTATION_TIME_CONFLICT,
    PRESENTATION_PAST_TIME,
    PRESENTATION_NOT_OWNED_BY_USER,
    PRESENTATION_ALREADY_STARTED,

    // 슬라이드
    SLIDE_FILE_REQUIRED,
    SLIDE_INVALID_FORMAT,
    SLIDE_SIZE_EXCEEDED,
    SLIDE_UPLOAD_FAILED,
    SLIDE_NOT_FOUND,

    // 방/세션
    ROOM_NOT_FOUND,
    ROOM_ALREADY_FULL,
    ROOM_ALREADY_CLOSED,
    ROOM_NOT_STARTED,
    ROOM_ACCESS_DENIED,
    ROOM_TOKEN_INVALID,
    ROOM_TOKEN_EXPIRED,
    ROOM_USER_KICKED,
    ROOM_USER_NOT_FOUND,

    // WebRTC
    WEBRTC_CONNECTION_FAILED,
    WEBRTC_PEER_NOT_FOUND,

    // 채팅
    CHAT_MESSAGE_REQUIRED,
    CHAT_MESSAGE_TOO_LONG,
    CHAT_RATE_LIMIT_EXCEEDED,

    // ========== 관리자 (ADMIN) ==========
    ADMIN_USER_SEARCH_FAILED,
    ADMIN_CANNOT_BAN_ADMIN,
    ADMIN_CANNOT_MODIFY_SELF,
    ADMIN_INVALID_ROLE,
    ADMIN_BAN_REASON_REQUIRED,
    AUDIT_LOG_NOT_FOUND,

    // ========== 카테고리 (CATEGORY) ==========
    CATEGORY_NOT_FOUND,
    CATEGORY_DUPLICATED,
    CATEGORY_HAS_ITEMS,

    // ========== 캐시 (CACHE) ==========
    CACHE_CONNECTION_ERROR,
    CACHE_OPERATION_FAILED,

    // ========== 외부 서비스 (EXTERNAL) ==========
    EXTERNAL_API_ERROR,
    EXTERNAL_API_TIMEOUT,

    // ========== 게스트 (GUEST) ==========
    GUEST_USER_NOT_FOUND,
    GUEST_USER_UNEXPECTED_EXIST,
}